// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user.proto

#include "user.pb.h"
#include "user.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Kuser {

static const char* UserServiceRpc_method_names[] = {
  "/Kuser.UserServiceRpc/Login",
  "/Kuser.UserServiceRpc/Register",
};

std::unique_ptr< UserServiceRpc::Stub> UserServiceRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserServiceRpc::Stub> stub(new UserServiceRpc::Stub(channel));
  return stub;
}

UserServiceRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Login_(UserServiceRpc_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Register_(UserServiceRpc_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserServiceRpc::Stub::Login(::grpc::ClientContext* context, const ::Kuser::LoginRequest& request, ::Kuser::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Login_, context, request, response);
}

void UserServiceRpc::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::Kuser::LoginRequest* request, ::Kuser::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void UserServiceRpc::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Kuser::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void UserServiceRpc::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::Kuser::LoginRequest* request, ::Kuser::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

void UserServiceRpc::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Kuser::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Kuser::LoginResponse>* UserServiceRpc::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::Kuser::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Kuser::LoginResponse>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Kuser::LoginResponse>* UserServiceRpc::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::Kuser::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Kuser::LoginResponse>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, false);
}

::grpc::Status UserServiceRpc::Stub::Register(::grpc::ClientContext* context, const ::Kuser::RegisterRequest& request, ::Kuser::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Register_, context, request, response);
}

void UserServiceRpc::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::Kuser::RegisterRequest* request, ::Kuser::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void UserServiceRpc::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Kuser::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void UserServiceRpc::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::Kuser::RegisterRequest* request, ::Kuser::RegisterResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

void UserServiceRpc::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Kuser::RegisterResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Kuser::RegisterResponse>* UserServiceRpc::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::Kuser::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Kuser::RegisterResponse>::Create(channel_.get(), cq, rpcmethod_Register_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Kuser::RegisterResponse>* UserServiceRpc::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::Kuser::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Kuser::RegisterResponse>::Create(channel_.get(), cq, rpcmethod_Register_, context, request, false);
}

UserServiceRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserServiceRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserServiceRpc::Service, ::Kuser::LoginRequest, ::Kuser::LoginResponse>(
          [](UserServiceRpc::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::Kuser::LoginRequest* req,
             ::Kuser::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserServiceRpc_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserServiceRpc::Service, ::Kuser::RegisterRequest, ::Kuser::RegisterResponse>(
          [](UserServiceRpc::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::Kuser::RegisterRequest* req,
             ::Kuser::RegisterResponse* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
}

UserServiceRpc::Service::~Service() {
}

::grpc::Status UserServiceRpc::Service::Login(::grpc::ServerContext* context, const ::Kuser::LoginRequest* request, ::Kuser::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserServiceRpc::Service::Register(::grpc::ServerContext* context, const ::Kuser::RegisterRequest* request, ::Kuser::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Kuser

